apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-deploy
  labels:
    app: web
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.hello-world: glob:hello-world*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hello-world
        image: Kartik-1611/hello-world-repo
        ports:
        - containerPort: 80
